#!/usr/bin/env bash

[ "$PLAYER_EVENT" = "change" ] || [ "$PLAYER_EVENT" = "start" ] || exit 0

songimage=$(playerctl metadata --format "{{ mpris:artUrl }}")
songname=$(playerctl metadata --format "{{ title }}")
song=$(playerctl metadata --format "Artist: {{ artist }}\nAlbum: {{ album }}")

wget -O /tmp/songimage.png $songimage

notify-send -i /tmp/songimage.png "$songname" "$song"

rm /tmp/songimage.png
