#!/usr/bin/env bash

WORKDIR=$(pwd)

_ags() {
  PID=$(pgrep -f 'gjs -m /run/user/1000/ags.js')

  if [[ -n "$PID" ]]; then
    echo "killing ags process"
    kill "$PID"
  fi

  ags run &
}

_scss() {
  sass "$WORKDIR"/scss/style.scss /tmp/style.css
  _ags
}

_ags

inotifywait --quiet --monitor --event create,modify,delete --recursive $WORKDIR | while read DIRECTORY EVENT FILE; do
  file_extension=${FILE##*.}
  case $file_extension in
  ts|tsx)
    echo "reload ags..."
    _ags
    ;;
  scss)
    echo "reload scss..."
    _scss
    ;;
  esac
done
