#!/usr/bin/env bash

WORKDIR="$HOME/.config/ags"

_ags() {
  PID=$(pgrep -f 'gjs -m /run/user/1000/ags.js')

  if [[ -n "$PID" ]]; then
    echo "killing ags process"
    kill "$PID"
  fi

  sleep 0.5 &
  ags run &
}

_scss() {
  sass "$WORKDIR"/scss/style.scss /tmp/style.css
  _ags
}

_ags

inotifywait --quiet --monitor --event create,modify,delete --recursive "$WORKDIR" | while read DIRECTORY EVENT FILE; do
  file_extension=${FILE##*.}
  case $file_extension in
  ts|tsx)
    if [[ $DIRECTORY == "$WORKDIR"* ]]; then
      echo "reload ags..."
      _ags
    fi
    ;;
  scss)
    if [[ $DIRECTORY == "$WORKDIR"* ]]; then
      echo "reload scss..."
      _scss
    fi
    ;;
  esac
done
