#!/usr/bin/env bash

set -eu

root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
"$root/plugin/imagecache/build-imagecache"

import_path="$root/plugin/imagecache/qml"
shell_icon_theme="$(gsettings get org.gnome.desktop.interface icon-theme 2>/dev/null || :)"
case "$shell_icon_theme" in
    \'*\')
        shell_icon_theme="${shell_icon_theme#\'}"
        shell_icon_theme="${shell_icon_theme%\'}"
        ;;
    *) shell_icon_theme="" ;;
esac
sownteeshell_jemalloc_conf="thp:never,narenas:4,dirty_decay_ms:3000"
export QML_IMPORT_PATH="$import_path${QML_IMPORT_PATH:+:$QML_IMPORT_PATH}"
export QML2_IMPORT_PATH="$import_path${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}"
export MALLOC_CONF="${MALLOC_CONF:+$MALLOC_CONF,}$sownteeshell_jemalloc_conf"
export QS_ICON_THEME="${QS_ICON_THEME:-${shell_icon_theme:-WhiteSur}}"
exec quickshell -p "$root/shell.qml" "$@"
