#!/bin/bash

# Niri Transform - Rotate display orientation (sownteedev)
# Usage: transform left|right

CONFIG="$HOME/.config/niri/include/outputs.kdl"

FOCUSED_JSON=$(niri msg -j focused-output)
OUTPUT=$(echo "$FOCUSED_JSON" | jq -r '.name')
ALL_OUTPUTS=$(niri msg -j outputs)
SYNC_RESULT=$(python3 "$HOME/Dotfiles/quickshell/scripts/display_output_config.py" "$CONFIG" "$(echo "$ALL_OUTPUTS" | jq -c '[.[]]')") || exit 1
TARGET_OUTPUT=$(echo "$SYNC_RESULT" | jq -r --arg output "$OUTPUT" '.identities[$output] // $output')

current=$(awk "/output \"$TARGET_OUTPUT\" {/,/}/{if (\$1==\"transform\") print \$2}" "$CONFIG" | tr -d '"')

order=(normal 90 180 270)

if [[ "$1" == "left" ]]; then
    dir=1
elif [[ "$1" == "right" ]]; then
    dir=-1
else
    exit 1
fi

idx=0
for i in {1..4}; do
    if [[ "${order[$i-1]}" == "$current" ]]; then
        idx=$i
        break
    fi
done

if [[ $idx -eq 0 ]]; then
    idx=1
fi

next=$(( (idx - 1 + dir + 4) % 4 ))
next_transform="${order[$next]}"

sed -i "/output \"$TARGET_OUTPUT\" {/,/}/{s/transform \".*\"/transform \"$next_transform\"/}" "$CONFIG"
