#!/usr/bin/env bash

processes=("picom")
for process in "${processes[@]}"; do
    if pidof -q "$process"; then
        pkill -x "$process" > /dev/null; sleep 0.1
    fi
done

~/.config/awesome/signals/scripts/Picom/toggle --no-opacity &
feh -z --no-fehbg --bg-fill ~/.walls &
xss-lock awesome-client "awesome.emit_signal('toggle::lock')" &
