#!/usr/bin/env bash
STATUS=$(nmcli | grep wlp0s20f3 | awk 'FNR == 1 {print $2}')
SSID=$(iwgetid -r)
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

if [[ $STATUS == "connected" ]]; then
	nmcli radio wifi off
else
	nmcli radio wifi on
fi
