#!/bin/bash

# Niri Screen Recorder - Start/Stop screen recording (sownteedev)

if pgrep -f "gpu-screen-recorder" > /dev/null; then
    killall gpu-screen-recorder
else
	output_path="$HOME/Videos/recording_$(date +'%d-%m-%Y_%H:%M:%S').mp4"

	region=$(slurp -b '#00000090' -c '#fff' -w 2 -f %wx%h+%x+%y)
	if [ -z "$region" ]; then
        notify-send "🎥 Screen Recording" "Recording cancelled (no region selected)."
        exit 1
    fi

	notify-send "🎥 Screen Recording" "Started Recorder"
    gpu-screen-recorder \
        -w region \
		-region "$region" \
        -f 165 \
        -a default_output \
        -ac opus \
        -q very_high \
        -k h264 \
        -encoder cpu \
        -cr limited \
        -fm vfr \
		-o "$output_path"

	format=$(notify-send "🎥 Screen Recording" \
		"Recording saved! Choose format:" \
		--action='delete=Delete' \
		--action='mp4=MP4' \
		--action='mp3=MP3' \
		--wait)

	case "$format" in
		delete)
			rm -f "$output_path"
			exit 0
			;;
		mp4)
			final_path="$output_path"
			;;
		mp3)
			final_path="${output_path%.mp4}.mp3"
			ffmpeg -i "$output_path" -vn -acodec libmp3lame -b:a 192k "$final_path"
			rm -f "$output_path"
			;;
		*)
			final_path="$output_path"
			;;
	esac

	wl-copy file:/"$final_path" -t text/uri-list

	action=$(notify-send "🎥 Screen Recording" \
		"Saved to $final_path" \
		--action='open=Open' \
		--wait)

	case "$action" in
		open)
			vlc "$final_path" &
			;;
	esac
fi
