#!/usr/bin/env bash
#             __ _       _     _            _              _   _
#  _ __ ___  / _(_)     | |__ | |_   _  ___| |_ ___   ___ | |_| |__
# | '__/ _ \| |_| |_____| '_ \| | | | |/ _ \ __/ _ \ / _ \| __| '_ \
# | | | (_) |  _| |_____| |_) | | |_| |  __/ || (_) | (_) | |_| | | |
# |_|  \___/|_| |_|     |_.__/|_|\__,_|\___|\__\___/ \___/ \__|_| |_|

toggle() {
	STATUS="$(bluetoothctl show | grep Powered | awk '{print $2}')"
	if [ $STATUS == "yes" ]; then
		bluetoothctl power off
		notify-send -a "Bluetooth" --urgency=normal "Bluetooth" "Bluetooth has been turned off."
	else
		bluetoothctl power on
		notify-send -a "Bluetooth" --urgency=normal "Bluetooth" "Bluetooth has been turned on."
	fi
}

if [[ $1 == "--toggle" ]]; then
	toggle
fi
