require(... .. ".battery")
require(... .. ".brightness")
require(... .. ".volume")
require(... .. ".microphone")
require(... .. ".systems")
require(... .. ".uptime")
require(... .. ".weather")
require(... .. ".redshift")
require(... .. ".blur")

require(... .. ".network")
require(... .. ".bluetooth")
require(... .. ".airplane")
require(... .. ".dnd")
