#!/bin/bash
LAST_EVENT_FILE="/tmp/mute_toggle_last_event"
CURRENT_TIME=$(date +%s)

if [[ -f $LAST_EVENT_FILE ]]; then
    LAST_EVENT=$(cat $LAST_EVENT_FILE)
    if (( CURRENT_TIME - LAST_EVENT < 1 )); then
        exit 0
    fi
fi

echo $CURRENT_TIME > $LAST_EVENT_FILE
pactl set-sink-mute @DEFAULT_SINK@ toggle
