#!/usr/bin/env bash

pkill picom
while pgrep -u $UID -x picom >/dev/null; do sleep 0; done

case $1 in
--opacity)
	picom --config ~/.config/awesome/signals/scripts/Picom/picom.conf -b &
	;;
--no-opacity)
	picom --config ~/.config/awesome/signals/scripts/Picom/picom_no_opacity.conf -b &
	;;
esac
