#!/usr/bin/env bash

is_active=$(cat ~/.cache/transparency)

if [[ $is_active == *"true"* ]]; then
	echo false > ~/.cache/transparency
	pkill picom
	while pgrep -u $UID -x picom >/dev/null; do sleep 0; done
	picom --config ~/.config/awesome/signals/scripts/Picom/picom_no_opacity.conf -b &
else
	echo true > ~/.cache/transparency
	pkill picom
	while pgrep -u $UID -x picom >/dev/null; do sleep 0; done
	picom --config ~/.config/awesome/signals/scripts/Picom/picom.conf -b &
fi
