#!/usr/bin/env bash

color_dir="$HOME/.config/scripts/Themes"
rofi_command="rofi -dmenu -theme $HOME/.config/scripts/RiceSelect/RiceSelector.rasi"
wm=$(wmctrl -m | grep "Name:" | awk '{print $2}')

options=()
for file in "$color_dir"/*; do
	options+=("$(basename "$file")")
done

color=$(printf "%s\n" "${options[@]}" | $rofi_command)

source ~/.config/scripts/Themes/$color

write() {
	echo "$color" > "$HOME"/.theme
}

term() {
	sed -i -e "s/include .*/include $color.conf/" "$HOME"/.config/kitty/kitty.conf
    sed -i -e "s/colors: .*/colors: *$color/" ~/.config/alacritty/colors.yml
}

gtk() {
	sed -i -e "s/background:.*/background:$bg/"\
		   -e "s/background_alt:.*/background_alt:$bgl3/"\
		   -e "s/foreground:.*/foreground:$fg/"\
		   -e "s/accent:.*/accent:$accent/" ~/.themes/tethemes/gtk-2.0/gtkrc

	sed -i -e "s/background .*/background $bg;/"\
		   -e "s/background_alt .*/background_alt $bgl3;/"\
		   -e "s/background_urgent .*/background_urgent $bgl4;/"\
		   -e "s/foreground .*/foreground $fg;/"\
		   -e "s/accent .*/accent $accent;/" ~/.themes/tethemes/gtk-3.0/colors.css
}

dunst() {
	sed -i -e "s/background = .*/background = \"$bgd\"/g"\
		   -e "s/foreground = .*/foreground = \"$fg\"/g" ~/.config/configs/dunstrc
	killall dunst && dunst -conf "$HOME"/.config/configs/dunstrc
}

discord() {
	cat ~/.config/BetterDiscord/data/stable/themes/$color.css > ~/.config/BetterDiscord/data/stable/custom.css
}

spotify() {
	spicetify config color_scheme $color && spicetify apply
}

rofi(){
	echo '* { background: '$bgd'; background-alt: '$bgl'; border-color: '$bgl3'; foreground: '$fg'; }' > ~/.config/scripts/.theme_rofi.rasi
}

nvim() {
	RICETHEME=$(cat $HOME/.theme)
    reload="python $HOME/.config/scripts/reload_nvim.py"
    reload_cmd="$reload 'lua require(\"themes.switch\").settheme(\"$RICETHEME\")'"
    eval "$reload_cmd"
	new_line="vim.g.currentTheme = \"$RICETHEME\""
	sed -i "s/vim.g.currentTheme = .*/$new_line/" "$HOME/.config/nvim/lua/user/options.lua"
}

restart() {
	if [[ $wm == "bspwm" ]]; then
		bspc wm -r
	elif [[ $wm == "awesome" ]]; then
		awesome-client "awesome.restart()"
	fi
}

if [[ -n "$color" ]]; then
	write
	term
	gtk
	dunst
	spotify
	discord
	rofi
	nvim
	restart
fi


exit 0
