#!/usr/bin/env bash

color_dir="$HOME/.config/scripts/Themes"
rofi_command="rofi -dmenu -theme $HOME/.config/scripts/RiceSelect/RiceSelector.rasi"

options=()
for file in "$color_dir"/*; do
	options+=("$(basename "$file")")
done

color=$(printf "%s\n" "${options[@]}" | $rofi_command)

source ~/.config/scripts/Themes/$color

term() {
	sed -i -e "s/include .*/include $color.conf/" "$HOME"/.config/kitty/kitty.conf
    sed -i -e "s/colors: .*/colors: *$color/" ~/.config/alacritty/colors.yml
}

gtk() {
	sed -i -e "s/background:.*/background:$bg/"\
		   -e "s/background_alt:.*/background_alt:$bgl3/"\
		   -e "s/foreground:.*/foreground:$fg/"\
		   -e "s/accent:.*/accent:$accent/" ~/.themes/tethemes/gtk-2.0/gtkrc

	sed -i -e "s/background .*/background $bg;/"\
		   -e "s/background_alt .*/background_alt $bgl3;/"\
		   -e "s/background_urgent .*/background_urgent $bgl4;/"\
		   -e "s/foreground .*/foreground $fg;/"\
		   -e "s/accent .*/accent $accent;/" ~/.themes/tethemes/gtk-3.0/colors.css
}

dunst() {
	sed -i -e "s/background = .*/background = \"$bgd\"/g"\
		   -e "s/foreground = .*/foreground = \"$fg\"/g" ~/.config/scripts/dunstrc
	killall dunst && dunst -conf "$HOME"/.config/scripts/dunstrc
}

discord() {
	cat ~/.config/BetterDiscord/data/stable/themes/$color.css > ~/.config/BetterDiscord/data/stable/custom.css
}

spotify() {
	spicetify config color_scheme $color && spicetify apply
}

rofi(){
	echo '* { background: '$bgd'; background-alt: '$bgl'; border-color: '$bgl3'; foreground: '$fg'; }' > ~/.config/scripts/.theme_rofi.rasi
}

nvim() {
    reload="python $HOME/.config/scripts/reload_nvim.py"
    reload_cmd="$reload 'lua require(\"themes.switch\").settheme(\"$color\")'"
    eval "$reload_cmd"
	new_line="vim.g.currentTheme = \"$color\""
	sed -i "s/vim.g.currentTheme = .*/$new_line/" "$HOME/.config/nvim/lua/user/options.lua"
}

awesome() {
	sed -i -e "s/theme.background                                     = .*/theme.background                                     = \"$bg\"/"\
		   -e "s/theme.background_dark                                = .*/theme.background_dark                                = \"$bgd\"/"\
		   -e "s/theme.background_alt                                 = .*/theme.background_alt                                 = \"$bgl\"/"\
		   -e "s/theme.background_urgent                              = .*/theme.background_urgent                              = \"$bgl2\"/"\
		   -e "s/theme.background_urgent1                             = .*/theme.background_urgent1                             = \"$bgl3\"/"\
		   -e "s/theme.foreground                                     = .*/theme.foreground                                     = \"$fg\"/"\
		   -e "s/theme.red                                            = .*/theme.red                                            = \"$red\"/"\
		   -e "s/theme.green                                          = .*/theme.green                                          = \"$green\"/"\
		   -e "s/theme.blue                                           = .*/theme.blue                                           = \"$blue\"/"\
		   -e "s/theme.yellow                                         = .*/theme.yellow                                         = \"$yellow\"/"\
		   -e "s/theme.orange                                         = .*/theme.orange                                         = \"$orange\"/"\
		   -e "s/theme.violet                                         = .*/theme.violet                                         = \"$violet\"/"\
		   -e "s/theme.accent                                         = .*/theme.accent                                         = \"$accent\"/" ~/.config/awesome/themes/theme.lua
}

backup() {
	declare -a config_folders=("awesome" "alacritty" "zsh" "ranger" "scripts")
	declare -a data_folders=("BetterDiscord/data/stable" "spicetify/Themes")
	declare -a dot_folders=("fonts" "icons" "themes" "walls")

	rm -rf ~/dotfiles/{.config,.fonts,.icons,.themes,.walls,.local}
	mkdir -p ~/dotfiles/{.config,.fonts,.icons,.themes,.walls,.local}

	for folder in "${config_folders[@]}"; do
		cp -r ~/.config/"$folder" ~/dotfiles/.config/
	done

	for folder in "${data_folders[@]}"; do
		mkdir -p ~/dotfiles/.config/"$folder"
		cp -r ~/.config/"$folder"/* ~/dotfiles/.config/"$folder"
	done
	
	for folder in "${dot_folders[@]}"; do
		cp -r ~/."$folder"/* ~/dotfiles/.${folder}/
	done
	cp -r ~/.local/other/ ~/dotfiles/.local/ && cp -r ~/.local/bin/ ~/dotfiles/.local/
	rm -f ~/dotfiles/.Xresources && cp ~/.Xresources ~/dotfiles/
	mkdir -p ~/dotfiles/.config/firefox && cp -r ~/.mozilla/firefox/*.default-release/chrome/ ~/dotfiles/.config/firefox/
}

if [[ -n "$color" ]]; then
	term
	gtk
	dunst
	spotify
	discord
	rofi
	nvim
	awesome
	backup
	awesome-client "awesome.restart()"
fi


exit 0
