#!/usr/bin/env bash

rofi_command="rofi -dmenu -theme $HOME/.config/bspwm/scripts/RiceSelect/RiceSelector.rasi"

options=( "yoru" )

selected=$(printf "%s\n" "${options[@]}" | $rofi_command)

if [[ -n "$selected" ]]; then
	echo "$selected" > "$HOME"/.config/bspwm/.rice
	bspc wm -r
fi
