#!/usr/bin/env bash
set -euo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
runtime_home="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}"
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
dotfiles_config=$(cd -- "$script_dir/../.." && pwd)

palette="$config_home/gtk-3.0/colors.css"
settings_template="$dotfiles_config/gtk-3.0/settings.ini"
settings_target="$config_home/gtk-3.0/settings.ini"
core_runner="${SOWNTEE_CORE_RUNNER:-$HOME/Dotfiles/sownteeshell/backend/rust/core-daemon/run-core-daemon}"
lock_file="$runtime_home/sownteeshell-gtk3-theme-${UID}.lock"

if [[ ! -s "$palette" ]]; then
    exit 0
fi

mkdir -p "$config_home/gtk-3.0" "$data_home/themes"
exec 9>"$lock_file"
flock -w 5 9 || exit 0

mode="${SOWNTEESHELL_THEME_MODE:-}"
if [[ "$mode" != "light" && "$mode" != "dark" ]] && command -v gsettings >/dev/null 2>&1; then
    scheme=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null || true)
    case "$scheme" in
        *prefer-light*) mode="light" ;;
        *) mode="dark" ;;
    esac
fi
if [[ "$mode" != "light" ]]; then
    mode="dark"
fi

if [[ "$mode" == "dark" ]]; then
    base_theme="adw-gtk3-dark"
    prefer_dark=1
else
    base_theme="adw-gtk3"
    prefer_dark=0
fi

current_theme=""
if command -v gsettings >/dev/null 2>&1; then
    current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null || true)
    current_theme=${current_theme#\'}
    current_theme=${current_theme%\'}
fi
if [[ "$current_theme" == "SownteeShell-A" ]]; then
    slot="B"
else
    slot="A"
fi

theme_name="SownteeShell-$slot"
theme_root="$data_home/themes/$theme_name"
theme_dir="$theme_root/gtk-3.0"
mkdir -p "$theme_dir"

palette_temp=$(mktemp "$theme_dir/.colors.css.XXXXXX")
cp -- "$palette" "$palette_temp"
mv -f -- "$palette_temp" "$theme_dir/colors.css"

gtk_temp=$(mktemp "$theme_dir/.gtk.css.XXXXXX")
{
    printf '/* Generated by SownteeShell. Changes are replaced by Matugen. */\n'
    printf '@import url("/usr/share/themes/%s/gtk-3.0/gtk.css");\n' "$base_theme"
    printf '@import url("colors.css");\n'
} > "$gtk_temp"
mv -f -- "$gtk_temp" "$theme_dir/gtk.css"

dark_temp=$(mktemp "$theme_dir/.gtk-dark.css.XXXXXX")
printf '@import url("gtk.css");\n' > "$dark_temp"
mv -f -- "$dark_temp" "$theme_dir/gtk-dark.css"

index_temp=$(mktemp "$theme_root/.index.theme.XXXXXX")
{
    printf '[Desktop Entry]\n'
    printf 'Type=X-GNOME-Metatheme\n'
    printf 'Name=%s\n' "$theme_name"
    printf 'GtkTheme=%s\n' "$theme_name"
} > "$index_temp"
mv -f -- "$index_temp" "$theme_root/index.theme"

settings_temp=$(mktemp "$config_home/gtk-3.0/.settings.ini.XXXXXX")
awk -v theme="$theme_name" -v prefer_dark="$prefer_dark" '
    BEGIN {
        in_settings = 0
        found_settings = 0
        wrote_theme = 0
        wrote_prefer = 0
    }
    function write_missing() {
        if (!wrote_theme)
            print "gtk-theme-name=" theme
        if (!wrote_prefer)
            print "gtk-application-prefer-dark-theme=" prefer_dark
    }
    /^\[[^]]+\]$/ {
        if (in_settings)
            write_missing()
        in_settings = ($0 == "[Settings]")
        if (in_settings) {
            found_settings = 1
            wrote_theme = 0
            wrote_prefer = 0
        }
        print
        next
    }
    in_settings && /^gtk-theme-name[[:space:]]*=/ {
        if (!wrote_theme) {
            print "gtk-theme-name=" theme
            wrote_theme = 1
        }
        next
    }
    in_settings && /^gtk-application-prefer-dark-theme[[:space:]]*=/ {
        if (!wrote_prefer) {
            print "gtk-application-prefer-dark-theme=" prefer_dark
            wrote_prefer = 1
        }
        next
    }
    { print }
    END {
        if (in_settings)
            write_missing()
        if (!found_settings) {
            if (NR > 0)
                print ""
            print "[Settings]"
            print "gtk-theme-name=" theme
            print "gtk-application-prefer-dark-theme=" prefer_dark
        }
    }
' "$settings_template" > "$settings_temp"
mv -f -- "$settings_temp" "$settings_target"

ini_value() {
    local key="$1"
    awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$settings_target"
}
icon_theme=$(ini_value gtk-icon-theme-name)
cursor_theme=$(ini_value gtk-cursor-theme-name)
cursor_size=$(ini_value gtk-cursor-theme-size)
icon_theme=${icon_theme:-WhiteSur}
cursor_theme=${cursor_theme:-Dark_Cursor}
cursor_size=${cursor_size:-24}

if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface gtk-theme "$theme_name" 2>/dev/null || true
fi

if [[ -n "${DISPLAY:-}" && -x "$core_runner" ]]; then
    "$core_runner" theme-xsettings-apply \
        "$theme_name" "$icon_theme" "$cursor_theme" "$cursor_size" \
        >/dev/null 2>&1 || true
fi
