#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═

function hide() {

case "${RICETHEME}" in
    yoru|pamela)
        polybar-msg cmd hide | bspc config top_padding 5
        ;;
    z0mbi3)
        eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar close bar | bspc config left_padding 5
        ;;
    andrea)
        eww -c "$HOME"/.config/bspwm/rices/andrea/arin close-all | bspc config top_padding 5
        ;;
    *)
        echo "Error: Something fails dud.."
        ;;
esac

}

function unhide() {

case "${RICETHEME}" in
    yoru|pamela)
    	polybar-msg cmd show | bspc config top_padding 60
    	;;
    z0mbi3)
    	eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar open bar | bspc config left_padding 80
    	;;
    andrea)
    	eww -c "$HOME"/.config/bspwm/rices/andrea/arin open-many \
    	   search \
    	   apps \
    	   weather \
    	   music \
    	   system | bspc config top_padding 60
    	;;
    *)
    	echo "Error: Something fails dud.."
    	;;
esac

}

case $1 in
    -h | --hide | hide)
    	hide
        exit;;
    -u | --unhide | unhide)
    	unhide
    	exit;;
    *) # Invalid option
    	echo "Error: Invalid option"
    	exit;;
esac
