#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═

function hide() {

case "${RICETHEME}" in
esac

}

function unhide() {

case "${RICETHEME}" in
esac

}

case $1 in
    -h | --hide | hide)
    	hide
        exit;;
    -u | --unhide | unhide)
    	unhide
    	exit;;
    *)
    	echo "Error: Invalid option"
    	exit;;
esac
