#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═

case "$1" in
  --menu)
    rofi -show drun -theme $HOME/.config/configs/launcher.rasi & disown;;
  --terminal)
    alacritty & disown;;
  --update)
    alacritty --hold --class FloaTerm,alacritty -e Updates --update-system & disown;;
  --checkupdates)
    alacritty --hold --class Updating,alacritty -e Updates --print-updates & disown;;
  --ranger)
    alacritty --class Ranger,alacritty -e ranger & disown;;
  --nvim)
    alacritty -e nvim & disown;;
  --music)
    alacritty --class MusicPlayer,alacritty -e ncmpcpp & disown;;
  --opacity)
	~/.config/configs/picom/toggle --opacity & disown;;
  --noopacity)
	~/.config/configs/picom/toggle --no-opacity & disown;;

  #Apps
  --filemanager)
    thunar & disown;;
  --browser)
    google-chrome-stable & disown;;
  --editor)
    nvim & disown;;
  --telegram)
    telegram-desktop & disown;;
  --soundcontrol)
    pavucontrol & disown;;
  *)
esac
