require(... .. ".battery")
require(... .. ".bright")
require(... .. ".volume")
require(... .. ".microphone")
require(... .. ".systems")
require(... .. ".uptime")
require(... .. ".weather")
require(... .. ".redshift")
