require("signals.system.battery")
require("signals.system.bright")
require("signals.system.volume")
require("signals.system.microphone")
require("signals.system.systems")
require("signals.system.uptime")
require("signals.system.weather")
require("signals.system.redshift")
