pcall(require, "luarocks.loader")
require("awful.autofocus")
require("beautiful").init(require("gears").filesystem.get_configuration_dir() .. "themes/theme.lua")
require("themes.toggle")
require("config")
require("signals")
require("ui")
